city_code = {
       'KUU':'Kullu'
    ,  'CMB':'Colombo'
    ,  'GAU' : 'Guwahati'
    ,  'PNY': 'Pondicherry'
    ,  'JAI' : 'Jaipur'
    ,  'PGH' : 'Pantnagar'
    ,  'RPR'  : 'Raipur'
    ,  'ATQ' : 'Amritsar'
    ,  'PUT':'Puttaparthi'
    ,  'CJB' : 'Coimbatore'
    ,  'MAA': 'Chennai'
    ,  'HJR' : 'Khajuraho'
    ,  'DIB' : 'Dibrugarh'
    ,  'TIR' : 'Tirupati'
    ,  'IXJ' : 'Jammu'
    ,  'DED' : 'Dehradun'
    ,  'SHL' : 'Shillong'
    ,  'IXD' : 'Allahabad'
    ,  'COK' : 'Cochin'
    ,  'DXB' : 'Dubai'
    ,  'GWL' : 'Gwalior' 
    ,  'IXG' : 'Belgaum'
    ,  'STV' : 'Surat'
    ,  'TRZ' : 'Tiruchirapally'
    ,  'IXP' : 'Pathankot'
    ,  'IXM' : 'Madurai'
    ,  'HBX' : 'Hubli'
    ,  'SSE' : 'Sholapur'
    ,  'IXS' : 'Silchar'
    ,  'VTZ' : 'Visakhapatnam'
    ,  'CCJ' : 'Calicut'
    ,  'GOI' : 'Goa'
    ,  'IXL' : 'Leh'
    ,  'UDR' : 'Udaipur'
    ,  'BHO' : 'Bhopal'
    ,  'TEZ': 'Tezpur'
    ,  'SLV' : 'Shimla'
    ,  'BBI' : 'Bhubaneshwar'
    ,  'BKK' : 'Bangkok'
    ,  'IXZ' : 'Port%20Blair'
    ,  'PBD' : 'Porbandar'
    ,  'DIU': 'Diu'
    ,  'VGA' : 'Vijaywada'
    ,  'BLR' : 'Bengaluru'
    ,  'PNQ' : 'Pune'
    ,  'LKO' : 'Lucknow'
    ,  'BOM' : 'Mumbai'
    ,  'BHJ' :'Bhuj' 
    ,  'NDC' : 'Nanded'
    ,  'HYD' : 'Hyderabad'
    ,  'IXB' : 'Bagdogra'
    ,  'AGX' : 'Agatti%20Island'
    ,  'KNU' : 'Kanpur'
    ,  'GOP' : 'Gorakhpur'
    ,  'IXA' : 'Agartala'
    ,  'UJJ'  : 'Ujjain'
    ,  'IXY' : 'Kandla'
    ,  'DHM' : 'Dharamshala'
    ,  'LTU' : 'Latur'
    ,  'AGR' : 'Agra' 
    ,  'IXR': 'Ranchi'
    ,  'JGA' : 'Jamnagar'
    ,  'IXI' : 'Lilabari'
    ,  'JSA' : 'Jaisalmer'
    ,  'PAT' : 'Patna'
    ,  'IXC' : 'Chandigarh'
    ,  'LUH' : 'Ludhiana'
    ,  'RAJ' : 'Rajkot' 
    ,  'JLR' : 'Jabalpur'
    ,  'TCR' : 'Tuticorin'
    ,  'AMD' : 'Ahmedabad'
    ,  'VDY' : 'Vidyanagar'
    ,  'GAY' : 'Gaya'
    ,  'IDR' : 'Indore'
    ,  'KLH' : 'Kolhapur'
    ,  'IXE' : 'Mangalore'
    ,  'RJA' : 'Rajahmundry'
    ,  'IXW' : 'Jamshedpur'
    ,  'SXV' : 'Salem'
    ,  'AJL' : 'Aizawl'
    ,  'DEL' : 'Delhi'
    ,  'VNS' : 'Varanasi'
    ,  'MYQ' : 'Mysore'
    ,  'BDQ' : 'Vadodara'
    ,  'CCU' : 'Kolkata'
    ,  'DMU' : 'Dimapur'
    ,  'JDH' : 'Jodhpur'
    ,  'TNI' : 'Satna'
    ,  'JRH' : 'Jorhat'
    ,  'ISK' : 'Nasik'
    ,  'TRV' : 'Trivandrum'
    ,  'IXU' : 'Aurangabad'
    ,  'SXR' : 'Srinagar'
    ,  'BHU' : 'Bhavnagar'
    ,  'NAG' : 'Nagpur'
    ,  'REW' : 'Rewa'
    ,  'BEP' : 'Bellary'
    ,  'IMF' : 'Iimphal'
}
